name = "Talksy"
client_id = "177dd497355fe743fa747f74896d9015"
application_url = "https://talksy-production-322d.up.railway.app/"
embedded = true


[access_scopes]
scopes = "write_products"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://talksy-production-322d.up.railway.app/auth/callback",
  "https://talksy-production-322d.up.railway.app/auth/shopify/callback",
  "https://talksy-production-322d.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "https://hkdk.events/wosrrl2b1hj10n"

[app_proxy]
url =  "https://fj-hide-price-2cb5dddf8f25.herokuapp.com/api/proxy"
subpath = "store-pickup"
prefix = "apps"

[pos]
embedded = false

[app_preferences]
url = "https://fj-hide-price-2cb5dddf8f25.herokuapp.com/preferences"

[build]
automatically_update_urls_on_dev = false